CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER TABLE refresh_tokens RENAME COLUMN id TO key;
ALTER TABLE refresh_tokens ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE refresh_tokens DROP CONSTRAINT IF EXISTS refresh_tokens_pkey;
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_key_key UNIQUE (key);
